export const categories = [
  'Hair Salons',
  'Tattoo Parlors',
  'Piercing Studios',
  'Barbershops',
  'Nail Salons',
  'Spa & Wellness',
  'Beauty Supply',
];

export const locations = [
  'Colombo',
  'Kandy',
  'Galle',
  'Jaffna',
  'Negombo',
  'Matara',
  'Kurunegala',
  'Batticaloa',
];

export const reviews = {
  1: [
    { id: 'r1', user: 'Nimali P.', rating: 5, comment: 'Best balayage in Colombo! Shanika is a true artist. My hair looks amazing and so healthy.', date: '2026-02-17' },
    { id: 'r2', user: 'Dilini R.', rating: 4, comment: 'Great color work. Slightly long wait but the results were worth it.', date: '2026-02-16' },
  ],
  2: [
    { id: 'r3', user: 'Kasun B.', rating: 5, comment: 'Incredible detail work on my sleeve. Nuwan is one of the best tattoo artists in Sri Lanka, period.', date: '2026-02-15' },
    { id: 'r4', user: 'Sachini T.', rating: 5, comment: 'Super clean shop, amazing portfolio. My floral piece turned out perfect.', date: '2026-02-15' },
    { id: 'r5', user: 'Malith L.', rating: 4, comment: 'Great work but booking is tough — plan weeks ahead. Totally worth the wait though.', date: '2026-02-14' },
  ],
  3: [
    { id: 'r6', user: 'Tharushi K.', rating: 5, comment: 'Got my septum done here. Completely painless and the jewelry selection is amazing!', date: '2026-02-14' },
  ],
  5: [
    { id: 'r7', user: 'Amandi S.', rating: 5, comment: 'Best fade I have ever had. Roshan really takes his time and nails it every single visit.', date: '2026-02-13' },
    { id: 'r8', user: 'Devin W.', rating: 5, comment: 'Old school barbershop vibes with modern skills. Hot towel shave was incredible.', date: '2026-02-12' },
    { id: 'r9', user: 'Ravindu P.', rating: 4, comment: 'Great cuts but it gets busy on weekends. Book ahead or come on a weekday.', date: '2026-02-11' },
  ],
  7: [
    { id: 'r10', user: 'Priya N.', rating: 5, comment: 'My gel nails lasted 3 weeks without chipping. Chamari does phenomenal nail art too!', date: '2026-02-18' },
  ],
  9: [
    { id: 'r11', user: 'Iresha V.', rating: 5, comment: 'The hot stone massage was heavenly. Left feeling like a completely new person. Highly recommend!', date: '2026-02-10' },
    { id: 'r12', user: 'Kamani J.', rating: 4, comment: 'Beautiful spa, great ambiance. The facial was excellent. Parking is a bit tricky.', date: '2026-02-09' },
  ],
  15: [
    { id: 'r13', user: 'Mihindu D.', rating: 5, comment: 'Custom Japanese sleeve by Kenji. Absolute master of his craft. 10/10 would recommend.', date: '2026-02-18' },
  ],
};

export const ads = [
  {
    id: 1,
    title: 'Salon Lassana — Color & Styling Specialists',
    description:
      'Full-service hair salon in the heart of Colombo specializing in balayage, highlights, keratin treatments, and precision cuts. Our team of master stylists has 15+ years of experience. Walk-ins welcome. Free consultation for new clients. We use organic and cruelty-free products exclusively.',
    price: 3500,
    category: 'Hair Salons',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&h=400&fit=crop',
    date: '2026-02-15',
    seller: { name: 'Shanika Perera', phone: '077 123 4567', email: 'shanika@salonlassana.lk' },
    userId: 'seed_user',
  },
  {
    id: 2,
    title: 'Lanka Ink Tattoo Parlor — Custom Designs',
    description:
      'Award-winning tattoo studio specializing in custom designs, Japanese traditional, realism, and fine-line work. All artists have 10+ years of experience. Sterile environment with hospital-grade autoclaves. Free consultations. Portfolio available on Instagram. Walk-ins accepted for small pieces.',
    price: 5000,
    category: 'Tattoo Parlors',
    location: 'Kandy',
    image: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=600&h=400&fit=crop',
    date: '2026-02-14',
    seller: { name: 'Nuwan Fernando', phone: '071 234 5678', email: 'nuwan@lankaink.lk' },
    userId: 'seed_user',
  },
  {
    id: 3,
    title: 'Needle & Thread Piercing Studio',
    description:
      'Professional body piercing studio with certified piercers. We offer ear, nose, septum, lip, eyebrow, navel, and industrial piercings. Only implant-grade titanium and 14k gold jewelry used. Aftercare kits included with every piercing. Ages 16+ with valid ID (minors need parental consent).',
    price: 2000,
    category: 'Piercing Studios',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=600&h=400&fit=crop',
    date: '2026-02-13',
    seller: { name: 'Dinusha Silva', phone: '076 345 6789', email: 'dinusha@needleandthread.lk' },
    userId: 'seed_user',
  },
  {
    id: 4,
    title: 'Mangala Bridal — Hair & Makeup',
    description:
      'Luxury bridal and special occasion hair and makeup services. We bring the salon to you with our mobile team. Bridal packages include trial session, day-of styling, and touch-up kit. Serving Colombo and surrounding areas. Book at least 3 months in advance for wedding dates.',
    price: 15000,
    category: 'Hair Salons',
    location: 'Negombo',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop',
    date: '2026-02-12',
    seller: { name: 'Sanduni Jayawardena', phone: '077 456 7890', email: 'sanduni@mangalabridal.lk' },
    userId: 'seed_user',
  },
  {
    id: 5,
    title: "Roshan's Classic Barbershop — Fades & Grooming",
    description:
      'Old-school barbershop with modern techniques. Specializing in skin fades, tapers, beard sculpting, and hot towel shaves. Relaxed atmosphere with complimentary tea. Appointments and walk-ins both welcome. Senior and student discounts available.',
    price: 800,
    category: 'Barbershops',
    location: 'Galle',
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&h=400&fit=crop',
    date: '2026-02-11',
    seller: { name: 'Roshan Bandara', phone: '071 567 8901', email: 'roshan@roshanbarber.lk' },
    userId: 'seed_user',
  },
  {
    id: 6,
    title: 'Sacred Geometry Tattoo — Fine Line Art',
    description:
      'Boutique tattoo studio specializing in geometric, dotwork, and minimalist fine-line tattoos. Each piece is custom-designed for you. We use single-use needles and vegan inks. Consultation required before booking. Deposit holds your appointment.',
    price: 7500,
    category: 'Tattoo Parlors',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=600&h=400&fit=crop',
    date: '2026-02-10',
    seller: { name: 'Amal Ratnayake', phone: '076 678 9012', email: 'amal@sacredgeometrytattoo.lk' },
    userId: 'seed_user',
  },
  {
    id: 7,
    title: 'Polished Nails & Spa — Gel, Acrylics & Art',
    description:
      'Premium nail salon offering gel manicures, acrylic extensions, dip powder, nail art, and pedicures. We use top brands like OPI, Essie, and CND. Sanitized tools for every client. Monthly membership packages available with 20% off all services.',
    price: 2500,
    category: 'Nail Salons',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=400&fit=crop',
    date: '2026-02-16',
    seller: { name: 'Chamari Wickramasinghe', phone: '077 789 0123', email: 'chamari@polishednails.lk' },
    userId: 'seed_user',
  },
  {
    id: 8,
    title: 'Urban Edge Piercing — Ear Curation Experts',
    description:
      'Specializing in curated ear piercings and unique body modifications. We carry an extensive collection of premium jewelry from international brands. Multiple piercings in one session available. Aftercare consultations included. Follow us on Instagram for our ear styling work.',
    price: 3000,
    category: 'Piercing Studios',
    location: 'Kandy',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&h=400&fit=crop',
    date: '2026-02-09',
    seller: { name: 'Kavinda Herath', phone: '071 890 1234', email: 'kavinda@urbanedgepiercing.lk' },
    userId: 'seed_user',
  },
  {
    id: 9,
    title: 'Serenity Ayurveda Spa — Massage & Facials',
    description:
      'Full-service day spa offering traditional Ayurvedic, Swedish, deep tissue, and hot stone massages. Signature facials, herbal body wraps, and aromatherapy treatments. Couples packages available. Tranquil environment with private treatment rooms. Gift vouchers available.',
    price: 4500,
    category: 'Spa & Wellness',
    location: 'Galle',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop',
    date: '2026-02-08',
    seller: { name: 'Nethmi Gunawardena', phone: '076 901 2345', email: 'nethmi@serenityayurveda.lk' },
    userId: 'seed_user',
  },
  {
    id: 10,
    title: "The Grooming Room — Men's Premium Barbershop",
    description:
      "Upscale men's grooming lounge offering precision haircuts, beard trims, scalp treatments, and straight razor shaves. Complimentary king coconut or espresso with every service. Private grooming suites available for VIP clients.",
    price: 1500,
    category: 'Barbershops',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop',
    date: '2026-02-07',
    seller: { name: 'Mahesh Cooray', phone: '077 012 3456', email: 'mahesh@thegroomingroom.lk' },
    userId: 'seed_user',
  },
  {
    id: 11,
    title: 'Glow Beauty Supply — Professional Products',
    description:
      'Your one-stop shop for professional beauty supplies. We carry salon-grade hair color, styling tools, skincare products, and nail supplies. Brands include Redken, Wella, Olaplex, and GHD. Wholesale pricing available for licensed professionals. Free delivery in Colombo for orders over Rs. 10,000.',
    price: 1000,
    category: 'Beauty Supply',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=400&fit=crop',
    date: '2026-02-06',
    seller: { name: 'Nayana Dissanayake', phone: '071 111 2233', email: 'nayana@glowbeautysupply.lk' },
    userId: 'seed_user',
  },
  {
    id: 12,
    title: 'Black Rose Tattoo — Traditional & Neo-Trad',
    description:
      'Established tattoo shop with 3 resident artists specializing in traditional, neo-traditional, and blackwork. Flash designs available daily. Custom work by appointment. Walk-in Wednesdays with special pricing. Clean, professional, and friendly environment.',
    price: 3500,
    category: 'Tattoo Parlors',
    location: 'Matara',
    image: 'https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=600&h=400&fit=crop',
    date: '2026-02-05',
    seller: { name: 'Dhanushka Kumara', phone: '076 222 3344', email: 'dhanushka@blackrosetattoo.lk' },
    userId: 'seed_user',
  },
  {
    id: 13,
    title: 'Crystal Clear Skin Studio — Advanced Facials',
    description:
      'Medical-grade facial treatments including microdermabrasion, chemical peels, LED light therapy, and hydrafacials. Licensed estheticians with dermatology backgrounds. Customized skincare routines for every client. First visit includes complimentary skin analysis.',
    price: 6000,
    category: 'Spa & Wellness',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop',
    date: '2026-02-04',
    seller: { name: 'Dr. Rashmi De Silva', phone: '077 333 4455', email: 'rashmi@crystalclearskin.lk' },
    userId: 'seed_user',
  },
  {
    id: 14,
    title: 'Curl & Co. — Natural Hair Specialists',
    description:
      'Salon dedicated to natural curls, coils, and textured hair. Services include wash & go styling, twist outs, silk presses, protective styles, and color. Certified stylists trained in international techniques. We celebrate all curl types.',
    price: 4000,
    category: 'Hair Salons',
    location: 'Kurunegala',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&h=400&fit=crop',
    date: '2026-02-03',
    seller: { name: 'Hasini Wijesinghe', phone: '071 444 5566', email: 'hasini@curlandco.lk' },
    userId: 'seed_user',
  },
  {
    id: 15,
    title: 'Rising Sun Tattoo — Japanese Irezumi Masters',
    description:
      'Specializing in traditional Japanese tattooing (Irezumi). Full sleeves, back pieces, and body suits by appointment. Our master artist trained in Tokyo for 5 years. Tebori (hand-poke) technique available. Consultations required for large-scale work.',
    price: 10000,
    category: 'Tattoo Parlors',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=600&h=400&fit=crop',
    date: '2026-02-17',
    seller: { name: 'Kenji Takahashi', phone: '076 555 6677', email: 'kenji@risingsuntattoo.lk' },
    userId: 'seed_user',
  },
  {
    id: 16,
    title: 'Rebel Body Piercing — Dermals & Exotic Piercings',
    description:
      'Advanced piercing studio specializing in surface anchors, dermal implants, and exotic piercings. Internationally certified. We stock exclusive jewelry from high-end brands. Numbing available for sensitive areas. 18+ only for certain piercings.',
    price: 3500,
    category: 'Piercing Studios',
    location: 'Jaffna',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&h=400&fit=crop',
    date: '2026-02-02',
    seller: { name: 'Ravi Shankar', phone: '077 666 7788', email: 'ravi@rebelbodypiercing.lk' },
    userId: 'seed_user',
  },
  {
    id: 17,
    title: 'Lacquer Lounge — Luxury Nail Experience',
    description:
      'High-end nail lounge offering hot towel manicures, spa pedicures, 3D nail art, and chrome finishes. Private manicure suites for groups and bridal parties. Non-toxic and vegan polish options. Appointments recommended.',
    price: 3000,
    category: 'Nail Salons',
    location: 'Colombo',
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=600&h=400&fit=crop',
    date: '2026-02-01',
    seller: { name: 'Vimasha Thenuwara', phone: '071 777 8899', email: 'vimasha@lacquerlounge.lk' },
    userId: 'seed_user',
  },
  {
    id: 18,
    title: 'Pro Beauty Warehouse — Tools & Equipment',
    description:
      'Professional beauty equipment supplier. Barber chairs, salon stations, tattoo machines, piercing supplies, sterilization equipment, and more. We serve salons, barbershops, and tattoo studios across Sri Lanka. Bulk discounts available. Same-day delivery in Colombo.',
    price: 1500,
    category: 'Beauty Supply',
    location: 'Negombo',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=400&fit=crop',
    date: '2026-01-30',
    seller: { name: 'Dasun Rajapaksha', phone: '076 888 9900', email: 'dasun@probeautywarehouse.lk' },
    userId: 'seed_user',
  },
  {
    id: 19,
    title: 'Zen Ayurveda Center — Holistic Body Treatments',
    description:
      'Holistic wellness center offering traditional Ayurvedic massage, herbal steam baths, reflexology, and detox body wraps. Certified therapists with 10+ years of experience. Infrared sauna sessions available. Perfect for stress relief and recovery. Package deals for regular clients.',
    price: 4000,
    category: 'Spa & Wellness',
    location: 'Kandy',
    image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&h=400&fit=crop',
    date: '2026-01-28',
    seller: { name: 'Lakshmi Weerasinghe', phone: '077 999 0011', email: 'lakshmi@zenayurveda.lk' },
    userId: 'seed_user',
  },
  {
    id: 20,
    title: 'Sharp Cuts Barbershop — Kids & Family Friendly',
    description:
      "Family-friendly barbershop with a dedicated kids area including gaming consoles and cartoons. Specializing in all hair types. Kids cuts, men's fades, line-ups, and beard grooming. Patient barbers experienced with children. First haircut certificate for little ones!",
    price: 500,
    category: 'Barbershops',
    location: 'Batticaloa',
    image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&h=400&fit=crop',
    date: '2026-01-25',
    seller: { name: 'Tharindu Jayasena', phone: '071 100 2233', email: 'tharindu@sharpcutsbarber.lk' },
    userId: 'seed_user',
  },
];
